[package]
name = "enose_project"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.35", features = ["full"] }
rand = "0.8"